name: CI

on:
  pull_request:

env:
  node_version: 20
  pnpm_version: 8

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpm_version }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run formatter
        run: pnpm format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpm_version }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run linter
        run: pnpm lint
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpm_version }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run check
        run: pnpm check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpm_version }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpm_version }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Sync sveltekit
        run: pnpm check
      - name: Build docs
        run: pnpm build:docs
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Sync sveltekit
        run: pnpm check
      - name: Build package
        run: pnpm build:package
